### ISSUE TITLE
Change Public to Open

### ISSUE THREAD

**Issue by gwsounddsg** [ExistentialAudio/SwiftOSC#39]
This is a feature request. 

Currently the upper level classes (eg: `OSCClient`) are declared as `public`, and it would be great if they were declared `open`. Because this library is mostly about networking, it's difficult to write unit tests without being able to write mocks for these classes. But I understand not wanting people to subclass these classes. Another compromise would be to supply mock classes directly in the library, then you retain your access control 

I'd be happy to do the work on this either way and submit a pull request if you think this makes sense.

Thanks, 
GW

**Comment by devinroth** [comment]
Sure works for me. Go for it. Thanks.
