### ISSUE TITLE
OSCServer not receiving

### ISSUE THREAD

**Issue by gwsounddsg** [ExistentialAudio/SwiftOSC#42]
After creating a basic `OSCServer` and conforming to `OSCServerDelegate`, the conforming class doesn't receive any OSC message. 

I added you to a private repo that's super super basic to show it not working.

**Comment by gwsounddsg** [comment]
The repo is private and called OSCTesting

**Comment by devinroth** [comment]
What are you sending to it?

**Comment by devinroth** [comment]
You should leave the address blank. It doesn't do what you think it does. 

server = OSCServer(address: "", port: 8080)

**Comment by devinroth** [comment]
I should probably add a wiki for this repo.

**Comment by gwsounddsg** [comment]
Okay, that's what I was doing wrong. If you'd like help with the Wiki, I'd be happy to help out.

**Comment by devinroth** [comment]
That would be awesome I would definitely appreciate the help. Let’s start a new thread to discuss the wiki.

**Comment by gwsounddsg** [comment]
Totally. This repo has been super helpful. I'd love to contribute as much as I can.
