### ISSUE TITLE
WatchOS Compatibility

### ISSUE THREAD

**Issue by codekrafter** [ExistentialAudio/SwiftOSC#44]
I am working on an app that needs to use OSC on a WatchOS app. Currently you cannot use this library with WatchOS and I am wondering if there are plans to add support for it.

**Comment by devinroth** [comment]
Not currently but I don't think it would be hard to add. I think I could easily add tvOS and watchOS.

**Comment by codekrafter** [comment]
that would be very helpful, if you want me to try to assemble a pull request to save you time I could attempt one, but I have minimal experience with CocoaPods

**Comment by devinroth** [comment]
I just added watchOS and tvOS support. It would be helpful if you could give it a try to before I push to CocoaPods.

**Comment by codekrafter** [comment]
Unlike the iOS and macOS projects, I had to adjust the team under the signing section of the watchOS and tvOS projects. This let it compile correctly, but it leads to runtime error "code signature invalid" for the framework that makes it so the library cannot be loaded.

**Comment by devinroth** [comment]
Could you send me a screenshot?

**Comment by codekrafter** [comment]
The watchOS project shows this and refuses to compile:
<img width="694" alt="Screen Shot 2020-01-21 at 12 52 18 PM" src="https://user-images.githubusercontent.com/11234290/72829751-5b4ad280-3c4d-11ea-93e2-194bf745df3e.png">
The iOS project shows this and compiles properly:
<img width="699" alt="Screen Shot 2020-01-21 at 12 52 35 PM" src="https://user-images.githubusercontent.com/11234290/72829752-5b4ad280-3c4d-11ea-88db-65e258904361.png">

When I substitute my team for the watchOS project it will compile, but when adding it as a framework, it compiles correctly on my iOS app (and I can use it properly to send osc), but when I embed it in my watchOS app/extension it throws this runtime error:
`dyld: Library not loaded: @rpath/SwiftOSC.framework/SwiftOSC
  Referenced from: /private/var/containers/Bundle/Application/E4537D24-0690-490F-884E-F92B6CB15E3A/ConsoleBuddy Watch App.app/PlugIns/ConsoleBuddy Watch Extension.appex/ConsoleBuddy Watch Extension
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/E4537D24-0690-490F-884E-F92B6CB15E3A/ConsoleBuddy Watch App.app/PlugIns/ConsoleBuddy Watch Extension.appex/Frameworks/SwiftOSC.framework/SwiftOSC: code signature invalid for '/private/var/containers/Bundle/Application/E4537D24-0690-490F-884E-F92B6CB15E3A/ConsoleBuddy Watch App.app/PlugIns/ConsoleBuddy Watch Extension.appex/Frameworks/SwiftOSC.framework/SwiftOSC'

	/private/var/containers/Bundle/Application/E4537D24-0690-490F-884E-F92B6CB15E3A/ConsoleBuddy Watch App.app/PlugIns/ConsoleBuddy Watch Extension.appex/Frameworks/SwiftOSC.framework/SwiftOSC: stat() failed with errno=1
(lldb) `

**Comment by devinroth** [comment]
Looks like a linking issue not a signing issue. I'll try to get a working example going.

**Comment by codekrafter** [comment]
If you look at the 4th line of the error it says it is rejecting the embedded library because `code signature invalid`, so it could be a combination of both

**Comment by devinroth** [comment]
I’m unable to reproduce it. Going to upload an example soon.

**Comment by devinroth** [comment]
Xcode is giving me some issues with github. Here's a dropbox link for now. 
https://www.dropbox.com/sh/pqhkm539qj3h24s/AAD0waxD9CSoFOfcRv_ZxYCva?dl=0

**Comment by codekrafter** [comment]
That example has no reference to SwiftOSC other than in the InterfaceController (maybe because it didn't like the movement between enviroments), but I still think that the problem is a signing error because the error message is saying code signature invalid for the embedded library

**Comment by devinroth** [comment]
Were you able to get my example running? Obviously you’ll have to relink the framework.

**Comment by codekrafter** [comment]
I got it working in a simulator (my project works in a simulator as well, just not on an actual device) but because of apple limiting the creation of profiles I could not deploy it to an actual device. I can just have the osc client/server run on the iOS app and have everything done with communication between them, to stick with what works.

**Comment by devinroth** [comment]
<img width="1231" alt="Screen Shot 2020-01-21 at 12 23 22 PM" src="https://user-images.githubusercontent.com/13010961/72840407-fa210000-3c48-11ea-9548-d44361f8b35c.png">
Try embedding SwiftOSC.

**Comment by devinroth** [comment]
And sorry I don't own an Apple Watch to actually test it on a real device.

**Comment by codekrafter** [comment]
I think I got it working on the iOS side, so I can just communicate between them to transmit messages.

**Comment by devinroth** [comment]
I'll push to cocoapods. Maybe it'll make a difference.
